<?php

namespace AdminBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    function findProduitName($nom)

    {
        $query=$this->getEntityManager()
            ->createQuery("select prod from AdminBundle:Produit prod 
                                where prod.nom LIKE :nom ")
            ->setParameter('nom','%'.$nom.'%');
        return $query->getResult();
    }
}
