<?php

namespace AdminBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{

    function findByQuestion($quest)
    {
        $query = $this->getEntityManager()->createQuery(
            "select v from AdminBundle:Question v  
                  WHERE v.question LIKE :quest 
                 ORDER BY v.question ASC"
        )->setParameter("quest",$quest.'%');


        return $query->getResult();
    }
}
